apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "auth-sim.fullname" . }}
  labels:
    {{- include "auth-sim.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "auth-sim.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "auth-sim.selectorLabels" . | nindent 8 }}
    spec:
      automountServiceAccountToken: false
      containers:
        - name: auth-sim
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            runAsNonRoot: true
            runAsUser: 65532
            runAsGroup: 65532
            allowPrivilegeEscalation: false
          env:
            - name: LAB_PUBLIC_ADDR
              value: 0.0.0.0:8080
            - name: LAB_ADMIN_ADDR
              value: 0.0.0.0:9090
            - name: LAB_ADMIN_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.adminSecret.name }}
                  key: {{ .Values.adminSecret.key }}
          ports:
            - name: public
              containerPort: 8080
              protocol: TCP
            - name: admin
              containerPort: 9090
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /readyz
              port: public
            initialDelaySeconds: 1
            periodSeconds: 2
            timeoutSeconds: 1
            failureThreshold: 15
          livenessProbe:
            httpGet:
              path: /healthz
              port: public
            initialDelaySeconds: 2
            periodSeconds: 5
            timeoutSeconds: 1
            failureThreshold: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
